### PR TITLE
Fix session expiry calculation

### PR DESCRIPTION
**Pull request by JOsacky**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

The current behavior calculates the delay before session expiry based on the time between the current system time and the expirationAt time. This delayBeforeExpiry time will change depending on the current system time.

## What is the new behavior?

The new behavior calculates the delay before session expiry based on the time between the beginning of the session and the expirationAt time. This makes it so that the delayBeforeExpiry is static and will always be 80% of the way from the beginning of the session to the expiresAt time.

## Additional context

I'm having some issues with expired tokens being used with my backend from the kotlin client, I'm hoping this helps alleviate some of that

### CODE REVIEW

**Review by jan-tennert — APPROVED** [review]
Thanks!

**Comment by jan-tennert** [comment]
@JOsacky I found a relatively major bug which causes sessions to be refreshed later than they should be. Might also cause your issues. A fix is on the way.

**Comment by JOsacky** [comment]
> @JOsacky I found a relatively major bug which causes sessions to be refreshed later than they should be. Might also cause your issues. A fix is on the way.

@jan-tennert thank you so much, I was seeing issues with refreshes happening later. I hope this fix helps, was this the commit you are referring to? 

https://github.com/supabase-community/supabase-kt/commit/9b73c03686f582d9069777b97caccfd006cc7c2f

**Comment by jan-tennert** [comment]
> > @JOsacky I found a relatively major bug which causes sessions to be refreshed later than they should be. Might also cause your issues. A fix is on the way.
> 
> @jan-tennert thank you so much, I was seeing issues with refreshes happening later. I hope this fix helps, was this the commit you are referring to?
> 
> [9b73c03](https://github.com/supabase-community/supabase-kt/commit/9b73c03686f582d9069777b97caccfd006cc7c2f)
> 
> Also thank you so much for coming back to this PR and letting me know!

Yes, let me know if you still get these issues after the fix.

**Comment by JOsacky** [comment]
> > > @JOsacky I found a relatively major bug which causes sessions to be refreshed later than they should be. Might also cause your issues. A fix is on the way.
> > 
> > 
> > @jan-tennert thank you so much, I was seeing issues with refreshes happening later. I hope this fix helps, was this the commit you are referring to?
> 
> Yes, let me know if you still get these issues after the fix.

Awesome, I will pull in the fix now and test

**Pull request merged**
