### PR TITLE
Add experimental support for IOS native target

### PR DESCRIPTION
**Pull request by jan-tennert**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

No support for IOS

## What is the new behavior?

Support for iosArm64, iosSimulatorArm64, and iosX64 including deeplinking (syntax same as android)

## Additional context

I cannot really test this PR as I don't have Mac myself to run a IOS Emulator on. I'm also not really familiar with IOS programming. Help would be appreciated

If you want to help, there is a version supporting IOS: `0.8.5-ios`

Currently needed: Feedback for deeplinking

To enable deeplinking, setup an [URL Scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app)
and set the host & scheme in the gotrue plugin:
```kotlin
install(GoTrue) {
    scheme = "supacompose"
    host = "login"
}
```
And on startup, call `client.handleDeeplinks(url)`

### CODE REVIEW

**Comment by jan-tennert** [comment]
Published a version ([0.8.0-beta-2-ios](https://github.com/supabase-community/supabase-kt/releases/tag/0.8.0-beta-2-ios)) with support for IOS, testing would be appreciated! If you also can test deep linking, the syntax is the same as Android but with URL Schemes

**Comment by jollygreenegiant** [comment]
For what it's worth, I've been testing this a bit in my own app and have not had any issues on the iOS side - things look great.  Haven't had the chance to test deep linking though

**Comment by jan-tennert** [comment]
> For what it's worth, I've been testing this a bit in my own app and have not had any issues on the iOS side - things look great. Haven't had the chance to test deep linking though

Great! Once the deep linking is settled, I'll merge this PR. I'm unsure about one thing: On Android supabase-kt pause and resumes auto refresh for the GoTrue session. Should this also be done on IOS/how would one implement this on IOS (using Kotlin of course)?

**Comment by seankcw** [comment]
@jan-tennert could you please add the support for Arm64 Simulator?
Related: https://stackoverflow.com/questions/73440638/cant-generate-arm64-simulator-with-kmm
image

**Comment by seankcw** [comment]
@jan-tennert could you please add the support for Arm64 simulator?
Related: https://stackoverflow.com/questions/73440638/cant-generate-arm64-simulator-with-kmm
image

**Comment by jan-tennert** [comment]
> @jan-tennert could you please add the support for Arm64 simulator targets? Related:
> 
>     * https://stackoverflow.com/questions/73440638/cant-generate-arm64-simulator-with-kmm
> 
>     * https://stackoverflow.com/a/74222279
> 
> 
> image

Published `0.8.4-ios-2`, let me know if that works!

**Comment by seankcw** [comment]
> > @jan-tennert could you please add the support for Arm64 simulator targets? Related:
> > ```
> > * https://stackoverflow.com/questions/73440638/cant-generate-arm64-simulator-with-kmm
> > 
> > * https://stackoverflow.com/a/74222279
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> Published `0.8.4-ios-2`, let me know if that works!

Thanks @jan-tennert !, so far I can build the debug version on simulator and device. I'll test the build with release in the coming weeks.

**Comment by seankcw** [comment]
I'm not able to call the api that required bearer token, somehow it will send two tokens in `Authorization` header.
Is it a bug?

Screenshot 2023-03-24 at 10 04 14 AM

**Comment by jan-tennert** [comment]
> I'm not able to call the api that required bearer token (e.g. `retrieveUserForCurrentSession()`, `refreshCurrentSession()`..), somehow it will send two tokens in `Authorization` header. Is it a bug?
> 
> Screenshot 2023-03-24 at 10 04 14 AM

Yes that was indeed a bug, ktor was adding an access token twice. Should be fixed in version `0.8.5-ios`

**Comment by seankcw** [comment]
@jan-tennert I tested 0.8.5 I am successfully log in with my account, but I haven't tested the deep linking on client-side project, because I'm doing deeplink/token verification in KMM directly (with MVI pattern).
I think the current version is still good to go.

**Comment by jan-tennert** [comment]
> @jan-tennert I tested 0.8.5 I can successfully log in with my account, but I haven't tested the deep linking on client-side project, because I'm doing deeplink/token verification in KMM directly (with MVI pattern). I think the current version is still good to go.

Alright, thanks! Then I'll merge this PR for now

**Comment by ldobransky** [comment]
I was testing it, but when deeplink is handled, in URL object are data, but method handleDeeplink don't save data. 
`
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool {
        SupaBaseHelper().handleDeeplinks(url: url)
        return true
    }
`
in handleDeeplinks I am calling `supabaseClient.handleDeeplinks(url)`
supabaseClient is shared from DI by Koin.

on Android is working well.
can somebody help me?

**Comment by jan-tennert** [comment]
> I was testing it, but when deeplink is handled, in URL object are data, but method handleDeeplink don't save data. When I am calling `supabaseClient.gotrue.currentAccessTokenOrNull()` I am getting null.
> `
> func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool {
>         SupaBaseHelper().handleDeeplinks(url: url)
>         return true
>     }
> `
> in handleDeeplinks I am calling `supabaseClient.handleDeeplinks(url)`
> supabaseClient is shared from DI by Koin.
> 
> on Android is working well.
> can somebody help me? I am using version 0.9.3.

Didnt test out deeplinking as I stated. Can you print out `url.fragment` and show me how it looks like? (dont show the access token)

**Comment by ldobransky** [comment]
I added `0.9.4-dev-1` logs bellow:
`
💚 DEBUG OAuthProvider.openOAuthlambda - Successfully opened provider url in safari 
💚 DEBUG SupabaseClient - Received deeplink with wrong scheme or host
`
between those two debug logs are mine what is mentioned above

**Comment by jan-tennert** [comment]
> I added `0.9.4-dev-1` logs bellow: `💚 DEBUG OAuthProvider.openOAuthlambda - Successfully opened provider url in safari 💚 DEBUG SupabaseClient - Received deeplink with wrong scheme or host` between those two debug logs are mine what is mentioned above

Okay so you can try to print out `url.scheme` and `url.host` and check if it matches with your GoTrue configuration? GoTrue checks if the received deeplink host & scheme matches with the provided one in the config:
https://github.com/supabase-community/supabase-kt/blob/3bde3ad83ca4ae5cd64f90d01b24f5dbaa47ed4c/GoTrue/src/iosMain/kotlin/io/github/jan/supabase/gotrue/IOS.kt#L11-L14

**Comment by ldobransky** [comment]
ok, you have right, I had wrong configuration in GoTrue, I changed it for correct one, but I am getting exception right now.
`KtorSupabaseHttpClient.request[async] - Request failed with TLS sessions are not supported on Native platform.
Uncaught Kotlin exception: io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost (GET) failed with message: TLS sessions are not supported on Native platform.` I think I had same exception when I was trying Email authentication, but on Android works both well. I have issue only for iOS

**Comment by jan-tennert** [comment]
> ok, you have right, I had wrong configuration in GoTrue, I changed it for correct one, but I am getting exception right now.
> `KtorSupabaseHttpClient.request[async] - Request failed with TLS sessions are not supported on Native platform.
> Uncaught Kotlin exception: io.github.jan.supabase.exceptions.HttpRequestException: HTTP request to http://localhost (GET) failed with message: TLS sessions are not supported on Native platform.` I think I had same exception when I was trying Email authentication, but on Android works both well. I have issue only for iOS

are you using the [darwin](https://ktor.io/docs/http-client-engines.html#darwin) ktor engine for ios? If not try it

**Comment by jan-tennert** [comment]
> really thanks for help, it helped :) 

No problem! I'll add additional information to the troubleshooting page

**Pull request merged**
